replicas: 1

persistence:
  enabled: false

extraEnvs:
  - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
    valueFrom:
      secretKeyRef:
        name: opensearch-secrets
        key: opensearch-admin-password
